config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/about'
  devise_for :users
  get '/search' => 'search#search'
  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  get 'users/:id/edit/leave' => 'users#leave', as: 'leave'
  # as: ''で名前付きルートにできる
  resources :games do
    resource :game_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @game = Game.find(params[:game_id])
    favorite = @game.favorites.new(user_id: current_user.id)
    favorite.save
    # redirect_to request.referer
  end

  def destroy
    @game = Game.find(params[:game_id])
    favorite = current_user.favorites.find_by(game_id: @game.id)
    favorite.destroy
    # redirect_to request.referer
  end

  private

  def redirect
    case params[:redirect_id].to_i
    when 0
      redirect_to games_path
    when 1
      redirect_to game_path(@game)
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorites.html.erb
<% if game.favorited_by?(current_user) %>
  <%= link_to game_favorites_path(game.id),method: :delete,remote: true do %>
    <span class="glyphicon glyphicon-heart" aria-hidden="true">
      <%= game.favorites.count %>
    </span>
  <% end %>
<% else %>
  <%= link_to game_favorites_path(game.id),method: :post,remote: true do %>
    <span class="glyphicon glyphicon-heart-empty" aria-hidden="true">
      <%= game.favorites.count %>
    </span>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorites_buttons_<%= @game.id %>").html("<%= j(render partial: 'favorites/favorites', locals: { game: @game}) %>");

app/views/favorites/destroy.js.erb
$("#favorites_buttons_<%= @game.id %>").html("<%= j(render partial: 'favorites/favorites', locals: {game: @game}) %>");