config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/about'
  devise_for :users
  get '/search' => 'search#search'
  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  get 'users/:id/edit/leave' => 'users#leave', as: 'leave'
  # as: ''で名前付きルートにできる
  resources :games do
    resource :game_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  attachment :image, destroy: false

  has_many :games
  has_many :favorites

  validates :name, presence: true, length: { maximum: 20 }
  validates :introduction, length: { maximum: 200 }

  # フォローフォロワーの処理
  # フォロー取得
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォロワー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :screen_user, only: [:edit, :update, :leave]

  def index
    @users = User.all.order(created_at: :desc)
    @users = User.all.page(params[:page]).per(6)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def leave
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end

  def screen_user
    if params[:id].to_i != current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table">
  <tbody>
  <% users.each do |user| %>
  <tr>
    <td><%= attachment_image_tag(user, :image, fallback: "46477.jpg", :size => '150x150') %></td>
    <td><%= user.name %></td>
    <td>フォロー数：<%= user.follower.count %></td>
    <td>フォロワー数：<%= user.followed.count %></td>
    <td>
      <% if current_user != user %>
        <% if current_user.following?(user) %>
          <%= link_to 'フォロー解除', user_relationships_path(user.id), method: :delete , class: "btn btn-danger"%>
        <% else %>
          <%= link_to 'フォローする', user_relationships_path(user.id),method: :POST , class: "btn btn-primary"%>
        <% end %>
      <% end %>
    </td>
    <td><%= link_to "詳細へ", user, class: "btn btn-default user_#{user.id}" %></td>
  </tr>
  <% end %>
  <tbody>
</table>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>
<div class="col-xs-12 base edit-padding">

<%= form_for(@user) do |f| %>
  <div class="col-xs-8 col-xs-offset-4">
    <%= render 'layouts/errors', model: f.object %>
    <%= f.label :"名前" %><br>
    <%= f.text_field :name, class: "col-xs-6 form-margin" %>
  </div>

  <div class="col-xs-8 col-xs-offset-4">
    <%= f.label :"プロフィール画像" %><br>
    <%= f.attachment_field :image, class: "col-xs-6 form-margin" %>
  </div>

  <div class="col-xs-8 col-xs-offset-4">
    <%= f.label :"自己紹介" %><br>
    <%= f.text_area :introduction, class: "col-xs-6 form-margin" %>
  </div>

  <div class="actions col-xs-8 col-xs-offset-4">
    <%= f.submit '編集完了', class: "col-xs-6 btn btn-primary form-margin" %>
<% end %>
  </div>

  <div class="actions col-xs-8 col-xs-offset-4">
    <%= link_to '退会',leave_path(@user), class: "col-xs-6 btn btn-danger edit_user_#{@user.id} form-margin" %>
  </div>

</div>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<div class="col-xs-12 base">
  <%= render 'users/index', users: @users %>
</div>
<div class="col-sx-12" class="text-center">
  <%= paginate @users %>
</div>

app/views/users/leave.html.erb
<div class="text-center create-order-btn-wrpper col-xs-12 base leave-padding">
  <div class="col-xs-4 col-xs-offset-4">
    <h3>本当に退会しますか？</h3>
  </div>
  <div class="col-xs-4 col-xs-offset-4">
    <p>退会を行うと現ユーザーでサービスが利用できなくなります。</p>
    <p>本当によろしいですか?</p>
  </div>
  <div class="col-xs-4 col-xs-offset-4">
    <%= link_to "退会しない", edit_user_path(@user), class: "btn btn-primary" %>
    <%= link_to "退会する", user_path(@user), method: :delete, class: "btn btn-danger" %>
  </div>
</div>

app/views/users/show.html.erb
<% if @user == current_user %>
  <h1>マイページ</h1>
<% else %>
  <h1>ユーザー詳細</h1>
<% end %>

<div class="col-xs-12 base show-padding">

  <div class="col-xs-4">
    <%= attachment_image_tag(@user, :image, fallback: "46477.jpg",:size => '250x250') %>
  </div>

  <div class="col-xs-4">
    <h2><%= @user.name %></h2>
    <div class="introduction">
      <h2>自己紹介</h2>
    </div>
    <div class="introduction">
      <%= @user.introduction %>
    </div>
  </div>

  <div class="col-xs-4">
    <table class="table introduction">
      <tbody>
        <tr>
          <th>フォロー中</th>
          <th><%= link_to @user.follower.count, user_follows_path(@user) %></th>
        </tr><br>
        <tr>
          <th>フォロワー</th>
          <th><%= link_to @user.followed.count, user_followers_path(@user) %></th>
        </tr>
      </tbody>
    </table>
    <% if current_user != @user %>
      <% if current_user.following?(@user) %>
      <div class="show-edit">
        <%= link_to 'フォロー外す', user_relationships_path(@user.id), method: :delete, class: "btn btn-danger" %>
      </div>
      <% else %>
      <div class="show-edit">
        <%= link_to 'フォローする', user_relationships_path(@user.id), method: :POST, class: "btn btn-primary" %>
      </div>
      <% end %>
    <% end %>
    <% if @user == current_user %>
    <div class="show-edit">
      <%= link_to 'プロフィール編集',edit_user_path(@user), class: "btn btn-primary edit_user_#{@user.id}" %>
    </div>
    <% end %>
  </div>

</div>