config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/about'
  devise_for :users
  get '/search' => 'search#search'
  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  get 'users/:id/edit/leave' => 'users#leave', as: 'leave'
  # as: ''で名前付きルートにできる
  resources :games do
    resource :game_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user, optional: true
  has_many :game_comments
  has_many :favorites

  attachment :image, destroy: false
  enum genre: {
    :その他 => 0, :アクション => 1, :シューティング => 2, :アドベンチャー => 3,
    :ロールプレイング => 4, :パズル => 5, :レースゲーム => 6, :シミュレーション => 7, :リズムゲーム => 8, :スポーツ => 9,
  }

  validates :title, presence: true, length: { maximum: 50 }
  validates :feeling, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.user_id = current_user.id
    if @game.save
      redirect_to games_path(@game.id)
    else
      @game.user_id = current_user.id
      render 'new'
    end
  end

  def index
    @games = Game.all.order(created_at: :desc)
    @games = Game.all.page(params[:page]).per(8)
  end

  def edit
    @game = Game.find(params[:id])
    screen_game(@game)
  end

  def show
    @game = Game.find(params[:id])
    @game_comment = GameComment.new
    @game_comments = @game.game_comments
  end

  def update
    @game = Game.find(params[:id])
    if @game.update(game_params)
      redirect_to game_path(@game)
    else
      render 'edit'
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path
  end

  private

  def game_params # アクション名、メソッド
    params.require(:game).permit(:title, :image, :feeling, :genre)
  end

  def screen_game(game)
    if game.user.id != current_user.id
      redirect_to game_path
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with model: @game,  local: true do |f| %>
  <div class="col-xs-8 col-xs-offset-4">
    <%= render 'layouts/errors', model: f.object %>
    <%= f.label :タイトル %><br>
    <%= f.text_field :title, class: "col-xs-6 form-margin" %>
  </div>

  <div class="col-xs-8 col-xs-offset-4">
    <%= f.label :投稿画像 %><br>
    <%= f.attachment_field :image, class: "col-xs-6 form-margin" %>
  </div>

  <div class="col-xs-8 col-xs-offset-4">
    <%= f.label :感想 %><br>
    <%= f.text_area :feeling, class: "col-xs-6 form-margin" %>
  </div>

  <div class="col-xs-8 col-xs-offset-4">
    <%= f.label :ジャンル %><br>
    <%= f.select :genre, [["その他"], ["アクション"], ["シューティング"], ["アドベンチャー"], ["ロールプレイング"], ["パズル"], ["レースゲーム"], ["シミュレーション"], ["リズムゲーム"], ["スポーツ"]], class: "col-xs-6 form-margin" %>
  </div>

  <div class="actions col-xs-8 col-xs-offset-4">
    <%= f.submit "完了", class: "btn btn-primary col-xs-6 form-margin" %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>投稿編集画面</h1>
<div class="col-xs-12 base edit-padding">
  <%= render 'games/form', game: @game %>
</div>

app/views/games/index.html.erb
<h1>ゲーム投稿一覧</h1>
<div class="col-xs-12 base">
  <% @games.each do |game| %>
    <div class="col-xs-3">
      <div class="imgWrap">
        <%= link_to(game) do %>
          <%= attachment_image_tag(game, :image, fallback: "no-image-mini.jpg", :size => '250x250') %>
        <% end %>
      </div>
      <h4>
        タイトル：
        <%= link_to(game) do %>
          <%= game.title %>
        <% end %>
      </h4>
      <p>
        ジャンル：
        <%= game.genre %>
      </p>
      <div id="favorites_buttons_<%= game.id %>">
        <%= render partial: 'favorites/favorites', locals: { game: game} %>
      </div>
      <p>
        コメント数：
        <%= game.game_comments.count %>
      </p>
    </div>
  <% end %>
</div>
<div class="col-sx-12" class="text-center">
  <%= paginate @games %>
</div>

app/views/games/new.html.erb
<h1>新規投稿</h1>
<div class="col-xs-12 base new-padding">
  <%= render 'games/form', game: @game %>
</div>

app/views/games/show.html.erb
<h1>投稿詳細</h1>
<div class="col-xs-12 base show-padding">

  <div class="col-xs-3">
    <h2><%= @game.user.name %></h2>
    <%= attachment_image_tag(@game.user, :image, fallback: "46477.jpg",:size => '150x150') %>
  </div>

  <div class="col-xs-5">
    <h2></h2>
    <h3>タイトル：<%= @game.title %></h3>
    <p>カテゴリ：<%= @game.genre %></p>
    <h2>感想</h2>
    <p><%= @game.feeling %></p>
    <%= attachment_image_tag(@game, :image, fallback: "no-image-mini.jpg",:size => '400x400') %>
    <div id="favorites_buttons_<%= @game.id %>">
      <%= render partial: 'favorites/favorites', locals: { game: @game} %>
    </div>
    <p>コメント数：<%= @game.game_comments.count %></p>
    <% if @game.user == current_user %>
      <%= link_to "Edit",edit_game_path(@game), class: "btn-sm btn-success edit_game_#{@game.id}" %>
      <%= link_to "Destroy",@game, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_game_#{@game.id}" %>
    <% end %>
  </div>

  <!--コメント機能-->
  <div class="col-xs-4">
    <div class="comment-form">
      <%= form_for [@game, @game_comment] do |f| %>
        <%= render 'layouts/errors', model: f.object %>
        <%= f.text_area :comment, size: "50x4" %>
        <%= f.submit 'コメントする', class: "btn btn-primary" %>
      <% end %>
    </div>
    <h3>コメント一覧</h3>
    <% @game_comments.each do |game_comment| %>
    <div class="col-xs-12">
      <div class="col-xs-3">
        <p><%= game_comment.user.name %></p><br>
      </div>
      <div class="col-xs-6">
        <p><%= game_comment.comment %></p>
      </div>
      <div class="col-xs-3">
        <% unless current_user != game_comment.user %>
          <%= link_to '削除',game_game_comments_path(game_comment.id),class: 'btn-sm btn-danger', method: :delete %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>

</div>