config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/about'
  devise_for :users
  get '/search' => 'search#search'
  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  get 'users/:id/edit/leave' => 'users#leave', as: 'leave'
  # as: ''で名前付きルートにできる
  resources :games do
    resource :game_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user, optional: true
  has_many :game_comments
  has_many :favorites

  attachment :image, destroy: false
  enum genre: {
    :その他 => 0, :アクション => 1, :シューティング => 2, :アドベンチャー => 3,
    :ロールプレイング => 4, :パズル => 5, :レースゲーム => 6, :シミュレーション => 7, :リズムゲーム => 8, :スポーツ => 9,
  }

  validates :title, presence: true, length: { maximum: 50 }
  validates :feeling, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/game_comment.rb
class GameComment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :game, optional: true

  validates :comment, presence: true
  validates :comment, length: { maximum: 200 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  attachment :image, destroy: false

  has_many :games
  has_many :favorites

  validates :name, presence: true, length: { maximum: 20 }
  validates :introduction, length: { maximum: 200 }

  # フォローフォロワーの処理
  # フォロー取得
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォロワー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  private

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

  def correct_user?(user)
    if current_user.nil?
      false
    else
      user.id.equal?(current_user.id)
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @game = Game.find(params[:game_id])
    favorite = @game.favorites.new(user_id: current_user.id)
    favorite.save
    # redirect_to request.referer
  end

  def destroy
    @game = Game.find(params[:game_id])
    favorite = current_user.favorites.find_by(game_id: @game.id)
    favorite.destroy
    # redirect_to request.referer
  end

  private

  def redirect
    case params[:redirect_id].to_i
    when 0
      redirect_to games_path
    when 1
      redirect_to game_path(@game)
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.user_id = current_user.id
    if @game.save
      redirect_to games_path(@game.id)
    else
      @game.user_id = current_user.id
      render 'new'
    end
  end

  def index
    @games = Game.all.order(created_at: :desc)
    @games = Game.all.page(params[:page]).per(8)
  end

  def edit
    @game = Game.find(params[:id])
    screen_game(@game)
  end

  def show
    @game = Game.find(params[:id])
    @game_comment = GameComment.new
    @game_comments = @game.game_comments
  end

  def update
    @game = Game.find(params[:id])
    if @game.update(game_params)
      redirect_to game_path(@game)
    else
      render 'edit'
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path
  end

  private

  def game_params # アクション名、メソッド
    params.require(:game).permit(:title, :image, :feeling, :genre)
  end

  def screen_game(game)
    if game.user.id != current_user.id
      redirect_to game_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params["search"]["model"]
    @content = params["search"]["content"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @model, @content)
  end

  private

  # 検索フォーム完全一致
  def match(model, content)
    if model == 'user'
      User.where(name: content)
    elsif model == 'game'
      Game.where(title: content)
    end
  end

  # 検索フォーム前方一致
  def forward(model, content)
    if model == 'user'
      User.where("name LIKE ?", "#{content}%")
    elsif model == 'game'
      Game.where("title LIKE ?", "#{content}%")
    end
  end

  # 検索フォーム後方一致
  def backward(model, content)
    if model == 'user'
      User.where("name LIKE ?", "%#{content}")
    elsif model == 'game'
      Game.where("title LIKE ?", "%#{content}")
    end
  end

  # 検索フォーム部分一致
  def partical(model, content)
    if model == 'user'
      User.where("name LIKE ?", "%#{content}%")
    elsif model == 'game'
      Game.where("title LIKE ?", "%#{content}%")
    end
  end

  def search_for(how, model, content)
    case how
    when 'match'
      match(model, content)
    when 'forward'
      forward(model, content)
    when 'backward'
      backward(model, content)
    when 'partical'
      partical(model, content)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :screen_user, only: [:edit, :update, :leave]

  def index
    @users = User.all.order(created_at: :desc)
    @users = User.all.page(params[:page]).per(6)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def leave
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end

  def screen_user
    if params[:id].to_i != current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/game_comments_helper.rb
module GameCommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(model.errors.count, "error") %>prohibited this model from being saved:</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container copyright">
    <div class="row">
     <p>© Infratop 2020</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default head">
  <div class="container">

    <div class="nav navbar-nav navbar-left">
      <%= link_to root_path do%>
        <%= image_tag 'icon.jpg',:size => '200x80' %>
      <% end %>
    </div>

    <% if user_signed_in? %>
    <div class="search">
      <span class="search-form">
        <%= form_tag(search_path, method: :get) do %>
          <%= text_field_tag 'search[content]' %>
          <%= select_tag 'search[model]', options_for_select({ "ユーザー" => "user", "タイトル" => "game" }) %>
          <%= select_tag 'search[how]', options_for_select({ "部分一致" => "partical", "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward"}) %>
          <span class="text_btn">
            <%= submit_tag '検索', class: "btn btn-default search_btn" %>
          </span>
        <% end %>
      </span>
    </div>
    <% end %>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
           <li>
            <%= link_to 'マイページ', user_path(current_user), class: 'show' %>
          </li>
           <li>
            <%= link_to '新規投稿', new_game_path(current_user), class: 'new' %>
          </li>
          <li>
            <%= link_to 'ユーザー一覧', users_path, class: 'users' %>
          </li>
          <li>
            <%= link_to '投稿一覧', games_path, class: 'games' %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_user_session_path,method: :delete, class: "btn" %>
          </li>
        <% else %>
          <li>
            <%= link_to 'top', root_path, class: 'top' %>
          </li>
          <li>
            <%= link_to 'about', homes_about_path, class: 'about' %>
          </li>
          <li>
            <%= link_to "ログイン", user_session_path, class: "about" %>
          </li>
          <li>
            <%= link_to 'sign up', new_user_registration_path, class: 'sign_up' %>
          </li>
        <% end %>
      </ul>

    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GAMEfeeling</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="row">
    <%= yield %>
      </div>
      <span id="back">
      <a href="#">
        <%= image_tag "arrow.png" %>
      </a>
    </span>
    </div>
    <div class="adjustment"></div>
    <%= render 'layouts/footer' %>
  </body>
</html>